config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', confirmations: 'users/confirmations' }
  devise_scope :user do
  	get '/users/sign_out' => 'devise/sessions#destroy'
	end

  authenticated :user do
    root :to => 'pages#welcome_page', as: :authenticated_root
  end
  root to: 'pages#landing_page'

  resources :clients do
    resources :target_clients do
      resources :contact_persons
      resources :addresses
  end
  end

  get 'selections/change_contact_person'
  get 'selections/change_address'
  get 'selections/change_target_client'
  get 'your_tasks' => 'pages#your_tasks'
  get 'your_requests' => 'pages#your_requests'
  get 'print_tasks' => 'pages#print_tasks'
  get 'update_notification_unread' => 'notifications#update_notification_unread'
  get 'update_notification_unread_all' => 'notifications#update_notification_unread_all'

  get 'location_report' => 'reports#location_report'

  resources :tasks do
    get 'history' => 'tasks#history'
    get 'resource_notes' => "tasks#resource_notes"
    get 'pass_task' => 'tasks#pass_task'
    post 'pass_task2' => 'tasks#pass_task2'
    collection do
      get :pass_all_tasks
      post :pass_all_tasks2
    end
  end

  get 'notifications/link_through'
  get 'notifications/index'

  # selections
  mount ActionCable.server => '/cable'


  require 'resque/server'
  mount Resque::Server, at: '/resque'


end

app/models/target_client.rb
class TargetClient < ApplicationRecord
  belongs_to :client
  has_many   :contact_persons
  has_many   :addresses

  accepts_nested_attributes_for :addresses

  validates :name, presence: true
end

app/controllers/target_clients_controller.rb
class TargetClientsController < ApplicationController
  def new
    @client = Client.find(params[:client_id])
    @target_client = @client.target_clients.build
    @address = @target_client.addresses.build
  end

  def create
    @client = Client.find(params[:client_id])
    @target_client = @client.target_clients.build(target_client_params)
    if @target_client.save
      flash[:success] = "Target Client created"
      redirect_to root_url
    else
      flash[:danger] = @target_client.errors.full_messages
      render action: :new
    end
  end

  def show
    @client = Client.find(params[:client_id])
    @target_client = TargetClient.find(params[:id])
    @addresses = @target_client.addresses.order(created_at: :asc)
    @contact_persons = @target_client.contact_persons.order(created_at: :asc)
  end

  private

  def target_client_params
    params.require(:client).permit(
      :id,
      :name,
      addresses_attributes: [
        :id,
        :first_line,
        :second_line,
        :city_town,
        :province,
        :country,
        :zipcode
      ]
    )
  end

end

app/views/target_clients/_address.html.erb
<div class="col-12 text-left">
  <div class="v-padding medium">
    <span class='small-index'>Address <%= @addresses.index(address) + 1 %></span>
    <%= address.first_line %> <%= address.second_line %> <%= address.city_town %>, <%= address.province %>, <%= address.country %> <%= address.zipcode%>
  </div>
</div>

app/views/target_clients/_contact_person.html.erb
<div class="col-12 text-left">
  <div class="v-padding medium">
    <span class='small-index bg-warning'>Contact <%= @contact_persons.index(contact_person) + 1 %></span>
    <p><%= contact_person.full_name %></p>
    <%= contact_person.contact_number %>
  </div>
</div>

app/views/target_clients/_target_client_form.html.erb
<%= simple_form_for @target_client, url: url, method: method do |f| %>
  <%= f.input :name %>
  <%= f.simple_fields_for :address do |ff| %>
    <%= ff.input :first_line %>
    <%= ff.input :second_line %>
    <%= ff.input :city_town %>
    <%= ff.input :province %>
    <%= ff.input :country%>
    <%= ff.input :zipcode %>
  <% end %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/target_clients/new.html.erb
<h3>New Target Client</h3>
<p>For <%= @client.name %></p>
<br>
<%= render 'target_client_form', url: client_target_clients_url(@client, @target_client), method: :post %>

app/views/target_clients/show.html.erb
<div class="text-center">
  <h3><%= @target_client.name %></h3>
  <p>Target Client of: <%= @client.name %></p>
  <br>
  <div class="options-container">
    <div class="row justify-content-center">
      <div class="col-md-3">
        <%= link_to 'ADD ADDRESS', new_client_target_client_address_url(@client, @target_client), class: 'option-button black-text bg-white' %>
      </div>
      <div class="col-md-3">
        <%= link_to 'ADD CONTACT PERSON', new_client_target_client_contact_person_url(@client, @target_client), class: 'option-button black-text bg-white' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3 v-padding large">
      <h4 class="text-left">Addresses</h4>
      <div class="row">
        <%= render partial: 'address', collection: @addresses, as: 'address' %>
      </div>
    </div>
    <div class="col-md-3 v-padding large">
      <h4 class="text-left">Contact Persons</h4>
      <div class="row">
        <%= render partial: 'contact_person', collection: @contact_persons, as: 'contact_person' %>
      </div>
    </div>
  </div>
</div>