config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', confirmations: 'users/confirmations' }
  devise_scope :user do
  	get '/users/sign_out' => 'devise/sessions#destroy'
	end

  authenticated :user do
    root :to => 'pages#welcome_page', as: :authenticated_root
  end
  root to: 'pages#landing_page'

  resources :clients do
    resources :target_clients do
      resources :contact_persons
      resources :addresses
  end
  end

  get 'selections/change_contact_person'
  get 'selections/change_address'
  get 'selections/change_target_client'
  get 'your_tasks' => 'pages#your_tasks'
  get 'your_requests' => 'pages#your_requests'
  get 'print_tasks' => 'pages#print_tasks'
  get 'update_notification_unread' => 'notifications#update_notification_unread'
  get 'update_notification_unread_all' => 'notifications#update_notification_unread_all'

  get 'location_report' => 'reports#location_report'

  resources :tasks do
    get 'history' => 'tasks#history'
    get 'resource_notes' => "tasks#resource_notes"
    get 'pass_task' => 'tasks#pass_task'
    post 'pass_task2' => 'tasks#pass_task2'
    collection do
      get :pass_all_tasks
      post :pass_all_tasks2
    end
  end

  get 'notifications/link_through'
  get 'notifications/index'

  # selections
  mount ActionCable.server => '/cable'


  require 'resque/server'
  mount Resque::Server, at: '/resque'


end

app/models/client.rb
class Client < ApplicationRecord
  has_many  :target_clients
  has_many  :contact_persons, through: :target_clients
  has_many   :addresses, through: :target_clients

  validates :name, presence: true
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def new
    @client = Client.new
    @address = @client.addresses.build
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      flash.now[:success] = "Client created"
      redirect_to root_url
    else
      flash.now[:danger] = @client.errors.full_messages
      render action: :new
    end
  end

  def show
    @client = Client.find(params[:id])
    @target_clients = @client.target_clients
  end

  private

  def client_params
    params.require(:client).permit(
      :id,
      :name
    )
  end

end

app/views/clients/_client_form.html.erb
<%= simple_form_for @client, url: url, method: method do |f| %>
  <%= f.input :name %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/clients/_target_client.html.erb
<%= link_to client_target_client_url(@client, target_client), class: 'target-client-link' do %>
  <div class="col-12 text-left">
    <div class="v-padding medium target-client-container">
      <span class='small-index'>Target Client <%= @target_clients.index(target_client) + 1 %></span>
      <p class=''><%= target_client.name %></p>
      <p class='small-font tab1'><%= target_client.addresses.first.complete %></p>
    </div>
  </div>
<% end %>

app/views/clients/new.html.erb
<h3>New Client</h3>
<%= render 'client_form', url: clients_url(@client), method: :post %>

app/views/clients/show.html.erb
<h3 class='text-center'><%= @client.name %></h3>
<div class="options-container text-center">
  <div class="row justify-content-center">
    <%= link_to 'ADD TARGET CLIENT', new_client_target_client_url(@client), class: 'option-button black-text bg-white' %>
  </div>
</div>
<div class="row">
  <div class="col-md-4 v-padding large">
    <h4 class="text-left">Target Clients</h4>
    <div class="row">
      <%= render partial: 'target_client', collection: @target_clients, as: 'target_client' %>
    </div>
  </div>
</div>