config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', confirmations: 'users/confirmations' }
  devise_scope :user do
  	get '/users/sign_out' => 'devise/sessions#destroy'
	end

  authenticated :user do
    root :to => 'pages#welcome_page', as: :authenticated_root
  end
  root to: 'pages#landing_page'

  resources :clients do
    resources :target_clients do
      resources :contact_persons
      resources :addresses
  end
  end

  get 'selections/change_contact_person'
  get 'selections/change_address'
  get 'selections/change_target_client'
  get 'your_tasks' => 'pages#your_tasks'
  get 'your_requests' => 'pages#your_requests'
  get 'print_tasks' => 'pages#print_tasks'
  get 'update_notification_unread' => 'notifications#update_notification_unread'
  get 'update_notification_unread_all' => 'notifications#update_notification_unread_all'

  get 'location_report' => 'reports#location_report'

  resources :tasks do
    get 'history' => 'tasks#history'
    get 'resource_notes' => "tasks#resource_notes"
    get 'pass_task' => 'tasks#pass_task'
    post 'pass_task2' => 'tasks#pass_task2'
    collection do
      get :pass_all_tasks
      post :pass_all_tasks2
    end
  end

  get 'notifications/link_through'
  get 'notifications/index'

  # selections
  mount ActionCable.server => '/cable'


  require 'resque/server'
  mount Resque::Server, at: '/resque'


end

app/views/pages/_client.html.erb
<%= link_to client_url(client), class: "selection" do %>
  <div class="col-12 selection v-padding">
    <%= client.name %>
  </div>
<% end %>

app/views/pages/_client_pane.html.erb
<div class="col-lg-2 col-md-3 d-none d-md-block">
  <div class="row h-padding v-padding large">
    <div class="col-12 text-center">
      <h3>Clients</h3>
    </div>
    <%= render partial: 'client', collection: @clients, as: 'client' %>
  </div>
</div>

app/views/pages/_nav_tabs.html.erb
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to "All", authenticated_root_url(status: "All", sort: {sort: sort2}), class: "nav-link #{ "active" if params[:status] == 'All'}" %>
  </li>
  <li class="nav-item">
    <%= link_to "Open", authenticated_root_url(status: "Open", sort: {sort: sort2}), class: "nav-link #{ "active" if params[:status] == 'Open'}"  %>
  </li>
  <li class="nav-item">
    <%= link_to "Scheduled", authenticated_root_url(status: "Scheduled", sort: {sort: sort2}), class: "nav-link #{ "active" if params[:status] == 'Scheduled'}"  %>
  </li>
  <li class="nav-item">
    <%= link_to "With Issues", authenticated_root_url(status: "With Issues", sort: {sort: sort2}), class: "nav-link #{ "active" if params[:status] == 'With Issues'}" %>
  </li>
</ul>

app/views/pages/_search_form.html.erb
<%= search_form_for @q_tasks, url: your_tasks_url, as: :q_tasks, id: "employments_search" do |f| %>
  <%= f.search_field :task_cont, type: 'text', placeholder: 'Search task', class: 'form-control ds-input' %>
<% end %>

app/views/pages/_search_form_welcome.html.erb
<%= search_form_for @q_tasks, url: root_url, as: :q_tasks, id: "employments_search" do |f| %>
  <%= f.search_field :task_cont, type: 'text', placeholder: 'Search task', class: 'form-control ds-input' %>
<% end %>

app/views/pages/_sort_bar.html.erb
<%# form_tag(root_path, method: :get, class: 'form-inline') do %>
  <%# collection_select :sort, :sort, @sort_values, :value, :key, {include_blank: 'Sort Here'}, {class: 'form-control select optional select-width'} %>
  <%# hidden_field_tag :status, params[:status] %>
  <%# submit_tag 'Sort', class: 'btn btn-primary' %>
<%# end %>

<div class="dropdown show">
  <div class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Sort By
  </div>

  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
    <%= link_to "Required Date Latest", authenticated_root_url(status: params[:status], sort: {sort: "required_date DESC"}), class: "dropdown-item" %>
    <%= link_to "Request Date Latest", authenticated_root_url(status: params[:status], sort: {sort: "created_at DESC"}), class: "dropdown-item" %>
    <%= link_to "Required Date Oldest", authenticated_root_url(status: params[:status], sort: {sort: "required_date ASC"}), class: "dropdown-item" %>
    <%= link_to "Request Date Oldest", authenticated_root_url(status: params[:status], sort: {sort: "created_at ASC"}), class: "dropdown-item" %>

  </div>
</div>

app/views/pages/_task2.html.erb
<div class='pb_avoid'>
  <span class="thick">Task# <%= task.id %></span>
  <div class="row">
    <div class="col-12">
      <div class="task-container-pdf">
        <hr class="pdf">
        <div class="row">
          <div class="col-6">
            <p><span class="thick">Required Date:</span> <%= better_date2(task.required_date) %></p>
            <p><span class="thick">Request Type: </span><%= task.request_type.name %></p>
            <p><span class="thick">Status: </span><%= task.status.name.upcase %></p>
            <p><span class="thick">Requestor: </span><%= task.user.full_name %> (<%= task.user.contact_number %>)</p>
          </div>
          <div class="col-6">
            <p><span class="thick">Client:</span> <%= task.client.name %></p>
            <p><span class="thick">Target Client:</span> <%= task.target_client.name %></p>
            <p><span class="thick">Contact:</span> <%= task.contact_person.full_name %> (<%= task.contact_person.contact_number %>)</p>
            <p><span class="thick">Resource: </span><%= task.resource.full_name %> (<%= task.resource.contact_number %>)</p>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <p><span class="thick">Address: </span><%= task.address.complete %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <p><span class="thick">Request Description: </span> <br> <%= task.request_description %></p>
            <p><span class="thick">Notes to Resource: </span> <br> <%= task.notes_to_resource %></p>
            <p><span class="thick">Resource Notes: </span> <br> <%= task.resource_notes%></p>
          </div>
        </div>
        <hr class="pdf">
      </div>
    </div>
  </div>
</div>

app/views/pages/_task_no_jq.html.erb
<div class="col-12">
  <div class="task-container small-font">
    <div class="col-12 v-padding" id="task_first_<%= @tasks.index(task)%>">
      <div class="row">
        <div class="col-12 col-md-12">
          <div class="row">
            <div class="col">
              <p><strong>Required Date:</strong> <%= better_date(task.required_date) %></p>
            </div>
            <div class="col-6 col-md-3">
              <p><strong>Request Type: </strong><%= task.request_type.name %></p>
            </div>
          </div>
          <hr>
        </div>
        <div class="col-12 col-md-3">

          <p><strong>Requestor:</strong></p>
          <p><%= task.user.full_name %></p>
          <p><%= task.user.contact_number %></p>
        </div>
        <div class="col-12 col-md-3">
          <p><strong>Client:</strong> <%= link_to task.client.name, client_url(task.client) %></p>
          <p><strong>Contact:</strong></p>
          <p><%= task.contact_person.full_name %></p>
          <p><%= task.contact_person.contact_number %></p>
        </div>
        <div class="col-12 col-md-3">
          <p><strong>Resource: </strong></p>
          <p><%= task.resource.full_name %></p>
          <p><%= task.resource.contact_number %></p>
        </div>
        <div class="col-12 col-md-3 text-center">
          <p><strong>Status:</strong></p>
          <div class="d-flex flex-row justify-content-center">

            <div class="medium-index bg-<%= status(task.status.name) %>"><%= task.status.name.upcase %></div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12 small-font " id="task_second_<%= @tasks.index(task) %>">
        <div class="space"></div>
      <div class="row">
        <div class="col-12 col-md-12">
          <div class="task-second-option">
            <p><strong>Address: </strong><%= task.address.complete %></p>
          </div>
        </div>
        <div class="col-12 col-md-4">
          <div class="task-second-option">
            <p><strong>Request Description: </strong> <br> <%= task.request_description %></p>
          </div>
        </div>
        <div class="col-12 col-md-4">
          <div class="task-second-option">
            <p><strong>Notes to Resource: </strong> <br> <%= task.notes_to_resource %></p>
          </div>
        </div>
        <div class="col-12 col-md-4">
          <div class="task-second-option">
            <p><strong>Resource Notes: </strong> <br> <%= task.resource_notes%></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12">
      <% if action_name == 'your_tasks' %>
        <%= link_to "Edit", edit_task_url(task), class:'btn btn-primary btn-sm white-font' if current_user == task.user %>
        <%= link_to "Add Resource Notes", edit_task_url(task, add_notes_only: true), class:'btn btn-primary btn-sm white-font' if current_user == task.resource %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/_task_pane.html.erb
<div class="col-lg-10 col-md-9">
  <div class="row h-padding v-padding large">
    <div class="col-12">
      <div class="row">
        <div class="col-6 col-md-8">
          <h3>Offshore's Tasks</h3>
          <div class="space"></div>
        </div>
        <div class="col-6 col-md-4">
          <div class="d-flex justify-content-end">
            <div class="p-2">
              <%= render 'search_form_welcome' %>
            </div>
            <div class="p-2">
              <%= render 'sort_bar' %>
            </div>
          </div>
        </div>
      </div>
    </div>

        <%= render 'nav_tabs' %>

    <%= render partial: 'task', collection: @tasks, as: 'task' %>
  </div>
  <hr>
  <div class="d-flex justify-content-center">
    <div class="p-2 text-center">
      <%= paginate @tasks, theme: 'twitter-bootstrap-4' %>
      <%= page_entries_info @tasks %>
    </div>
  </div>
</div>

app/views/pages/landing_page.html.erb
<div class="landing-container">
  <div class="landing-dashboard">
    <div class="dashboard-container">
      <div class="dashboard-title">
        <h1>Trackqer</h1>
        <h2>By Offshore</h2>
      </div>
      <div class="dashboard-text">
        <p>Tracking Requests and Progresses all with simplicity.</p>
      </div>
      <div class="dashboard-button-container">
        <%= link_to 'SIGN UP', new_user_registration_url, class: 'dashboard-button'%>
        &nbsp;
        &nbsp;
        &nbsp;
        &nbsp;
        <%= link_to 'LOG IN', new_user_session_url, class: 'login-button'%>
      </div>
    </div>
  </div>
</div>

app/views/pages/print_tasks.html.erb
<span class="thick"><%= current_user.full_name %>:</span> Tasks From <%= better_date(@start_date) %> to <%= better_date(@end_date) %>

<br>

<%= render partial: 'task2', collection: @tasks, as: 'task' %>

app/views/pages/welcome_page.html.erb
<div class="options-container h-padding">
  <div class="row align-items-center">
    <%= link_to 'ADD TASK', new_task_url, class: 'option-button black-text bg-white' %>
    <%= link_to 'ADD CLIENT', new_client_url, class: 'option-button black-text bg-white' %>
  </div>
</div>
<div class="row">
  <%= render 'client_pane' %>
  <%= render 'task_pane' %>
</div>

app/views/pages/your_requests.html.erb
<div class="col-lg-12 col-md-12">
  <div class="row h-padding v-padding large">
    <div class="col-12">
      <h3>My Requests</h3>
      <p><%= has_tasks?(@tasks) %></p>

    </div>
  </div>
  <%= render partial: 'task', collection: @tasks, as: 'task' %>
</div>

app/views/pages/your_tasks.html.erb
<div class="col-lg-12 col-md-12">
  <div class="row h-padding v-padding large">
    <div class="col-12">
      <div class="d-flex justify-content-between">
        <div class="p-2">
          <h3>My Tasks</h3>
        </div>
        <div class="p-2">
          <%= link_to 'Pass All Tasks', pass_all_tasks_tasks_url, class: 'btn btn-warning' %>
          <%= link_to '1 week', your_tasks_url(start_date: Time.zone.today, end_date: Time.zone.today + 7.days), class: 'btn btn-primary text-white' %>
          <%= link_to '2 weeks', your_tasks_url(start_date: Time.zone.today, end_date: Time.zone.today + 14.days), class: 'btn btn-primary text-white' %>
          <%= link_to '1 month', your_tasks_url(start_date: Time.zone.today, end_date: Time.zone.today + 1.month), class: 'btn btn-primary text-white' %>
          <%= link_to 'Print PDF', print_tasks_url(start_date: params[:start_date], end_date: params[:end_date], format: :pdf), class: 'btn btn-success text-white' %>
        </div>
      </div>
      <div class="d-flex flex-row-reverse">
        <div class="p-2">
          <%= render 'search_form' %>
        </div>
      </div>
      <p><%= has_tasks?(@tasks) %></p>
    </div>
  </div>
  <%= render partial: 'task', collection: @tasks, as: 'task' %>
  <hr>
  <div class="d-flex justify-content-center">
    <div class="p-2 text-center">
      <%= paginate @tasks, theme: 'twitter-bootstrap-4' %>
      <%= page_entries_info @tasks %>
    </div>
  </div>
</div>