config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', confirmations: 'users/confirmations' }
  devise_scope :user do
  	get '/users/sign_out' => 'devise/sessions#destroy'
	end

  authenticated :user do
    root :to => 'pages#welcome_page', as: :authenticated_root
  end
  root to: 'pages#landing_page'

  resources :clients do
    resources :target_clients do
      resources :contact_persons
      resources :addresses
  end
  end

  get 'selections/change_contact_person'
  get 'selections/change_address'
  get 'selections/change_target_client'
  get 'your_tasks' => 'pages#your_tasks'
  get 'your_requests' => 'pages#your_requests'
  get 'print_tasks' => 'pages#print_tasks'
  get 'update_notification_unread' => 'notifications#update_notification_unread'
  get 'update_notification_unread_all' => 'notifications#update_notification_unread_all'

  get 'location_report' => 'reports#location_report'

  resources :tasks do
    get 'history' => 'tasks#history'
    get 'resource_notes' => "tasks#resource_notes"
    get 'pass_task' => 'tasks#pass_task'
    post 'pass_task2' => 'tasks#pass_task2'
    collection do
      get :pass_all_tasks
      post :pass_all_tasks2
    end
  end

  get 'notifications/link_through'
  get 'notifications/index'

  # selections
  mount ActionCable.server => '/cable'


  require 'resque/server'
  mount Resque::Server, at: '/resque'


end

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <% if type == "notice" %>
    <div class="alert alert-success">
  <% elsif type == "alert" %>
    <div class="alert alert-danger">
  <% else %>
    <div class='alert alert-<%= "#{type}" %>'>
  <% end %>
  <a href="#" class="close" data-dismiss="alert">&#215;</a>
  <ul style="margin-bottom: 0.25rem; list-style:none;" >
    <li>
      <%= msg %>
    </li>
  </ul>
</div>
<% end %>

app/views/layouts/_form_layout.html.erb
<div class="container">
  <div class="space"></div>
  <div class="row form justify-content-center align-items-center">
    <div class="col-12 col-sm-10 col-md-6 ">
      <%= yield if in_form? %>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
  <%= link_to 'Tracker', root_url, class: 'navbar-brand' %>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', root_url, class:'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'My Tasks', your_tasks_url, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'My Requests', your_requests_url, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'Reports', location_report_url, class: 'nav-link' %>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class='navbar-text'>
        <div href="#" class: 'nav-link text-white'>
          <%= current_user.full_name %>
        </a>
      </li>
      <li class='nav-item'>
        <%= link_to "#{ number_of_notifications } NOTIFICATIONS", notifications_index_url, class: 'navbar-button bg-primary text-white' %>
      </li>
      <li>
        <%= link_to 'SIGN OUT', destroy_user_session_path, class: 'navbar-button' %>
      </li>
    </ul>
  </div>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

</nav>

app/views/layouts/_report_layout.html.erb
<%= render 'layouts/reports_bar' %>
<div class="container report">
  <div class="row form">
    <div class="col-12 col-sm-12 md-8">
      <%= yield if in_report? %>
    </div>
  </div>
</div>

app/views/layouts/_reports_bar.html.erb
<div class="options-container">
  <div class="row justify-content-center">
    <div class="col-md-2">
      <%= link_to 'LOCATION REPORT', location_report_url, class: 'option-button black-text bg-white' %>
    </div>
  </div>
</div>

app/views/layouts/_show_layout.html.erb
<div class="container show">
  <div class="row form justify-content-center align-items-center">
    <div class="col-12 col-sm-12">
      <%= yield if in_show? %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tracker</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' if user_signed_in? && !in_print? %>
    <%= render 'layouts/flash' %>
    <%= render 'layouts/form_layout' if in_form? %>
    <%= render 'layouts/show_layout' if in_show? %>
    <%= render 'layouts/report_layout' if in_report? %>
    <%= yield if controller_name == 'pages' && !in_show? %>


  </body>
</html>